In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ashishkumarjayswal/movies-dataset")

print("Path to dataset files:", path)

/home/zeltrox/miniconda3/envs/myenv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/ashishkumarjayswal/movies-dataset?dataset_version_number=1...

100%|██████████| 236k/236k [00:01<00:00, 150kB/s]

Extracting files...
Path to dataset files: /home/zeltrox/.cache/kagglehub/datasets/ashishkumarjayswal/movies-dataset/versions/1

In [9]:
import pandas as pd
df = pd.read_csv("movies-dataset/versions/1/movies.csv")
df.head()

,"name;""rating"";""genre"";""year"";""released"";""score"";""votes"";""director"";""writer"";""star"";""country"";""budget"";""gross"";""company"";""runtime""",Unnamed: 1,Unnamed: 2
0,"The Shining;""R"";""Drama"";1980;""June 13","1980 (United States)"";8.4;927000.0;""Stanley K...",NaN
1,"The Blue Lagoon;""R"";""Adventure"";1980;""July 2","1980 (United States)"";5.8;65000.0;""Randal Kle...",NaN
2,Star Wars: Episode V - The Empire Strikes Back...,"1980 (United States)"";8.7;1200000.0;""Irvin Ke...",NaN
3,"Airplane!;""PG"";""Comedy"";1980;""July 2","1980 (United States)"";7.7;221000.0;""Jim Abrah...",NaN
4,"Caddyshack;""R"";""Comedy"";1980;""July 25","1980 (United States)"";7.3;108000.0;""Harold Ra...",NaN

In [10]:
df.iloc[:,0].str.split(";",expand=True)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,The Shining,"""R""","""Drama""",1980,"""June 13",None,None,None,None,None,None,None,None,None,None
1,The Blue Lagoon,"""R""","""Adventure""",1980,"""July 2",None,None,None,None,None,None,None,None,None,None
2,Star Wars: Episode V - The Empire Strikes Back,"""PG""","""Action""",1980,"""June 20",None,None,None,None,None,None,None,None,None,None
3,Airplane!,"""PG""","""Comedy""",1980,"""July 2",None,None,None,None,None,None,None,None,None,None
4,Caddyshack,"""R""","""Comedy""",1980,"""July 25",None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,"""R""","""Comedy""",2001,"""February 1",None,None,None,None,None,None,None,None,None,None
3996,Human Nature,"""R""","""Comedy""",2001,"""September 12",None,None,None,None,None,None,None,None,None,None
3997,Made,"""R""","""Comedy""",2001,"""August 31",None,None,None,None,None,None,None,None,None,None
3998,One Night at McCool's,"""R""","""Comedy""",2001,"""April 27",None,None,None,None,None,None,None,None,None,None
3999,Dr. Dolittle 2,"""PG""","""Comedy""",2001,"""June 22",None,None,None,None,None,None,None,None,None,None

In [11]:

df[['movie_name','rating_target_audience','genre','release_year','release_date']]=df.iloc[:,0].str.split(";",expand=True).iloc[:,0:5]

In [12]:
df.head()

,"name;""rating"";""genre"";""year"";""released"";""score"";""votes"";""director"";""writer"";""star"";""country"";""budget"";""gross"";""company"";""runtime""",Unnamed: 1,Unnamed: 2,movie_name,rating_target_audience,genre,release_year,release_date
0,"The Shining;""R"";""Drama"";1980;""June 13","1980 (United States)"";8.4;927000.0;""Stanley K...",NaN,The Shining,"""R""","""Drama""",1980,"""June 13"
1,"The Blue Lagoon;""R"";""Adventure"";1980;""July 2","1980 (United States)"";5.8;65000.0;""Randal Kle...",NaN,The Blue Lagoon,"""R""","""Adventure""",1980,"""July 2"
2,Star Wars: Episode V - The Empire Strikes Back...,"1980 (United States)"";8.7;1200000.0;""Irvin Ke...",NaN,Star Wars: Episode V - The Empire Strikes Back,"""PG""","""Action""",1980,"""June 20"
3,"Airplane!;""PG"";""Comedy"";1980;""July 2","1980 (United States)"";7.7;221000.0;""Jim Abrah...",NaN,Airplane!,"""PG""","""Comedy""",1980,"""July 2"
4,"Caddyshack;""R"";""Comedy"";1980;""July 25","1980 (United States)"";7.3;108000.0;""Harold Ra...",NaN,Caddyshack,"""R""","""Comedy""",1980,"""July 25"

In [13]:
df.drop('name;"rating";"genre";"year";"released";"score";"votes";"director";"writer";"star";"country";"budget";"gross";"company";"runtime"',axis=1,inplace=True)

In [14]:
df.head()

,Unnamed: 1,Unnamed: 2,movie_name,rating_target_audience,genre,release_year,release_date
0,"1980 (United States)"";8.4;927000.0;""Stanley K...",NaN,The Shining,"""R""","""Drama""",1980,"""June 13"
1,"1980 (United States)"";5.8;65000.0;""Randal Kle...",NaN,The Blue Lagoon,"""R""","""Adventure""",1980,"""July 2"
2,"1980 (United States)"";8.7;1200000.0;""Irvin Ke...",NaN,Star Wars: Episode V - The Empire Strikes Back,"""PG""","""Action""",1980,"""June 20"
3,"1980 (United States)"";7.7;221000.0;""Jim Abrah...",NaN,Airplane!,"""PG""","""Comedy""",1980,"""July 2"
4,"1980 (United States)"";7.3;108000.0;""Harold Ra...",NaN,Caddyshack,"""R""","""Comedy""",1980,"""July 25"

In [ ]:
df["Unnamed: 2"].value_counts()
#this column is mostly empty, so we can drop it

Unnamed: 2
The";100.0                                     2
The";94.0                                      1
The";119.0                                     1
The";108.0                                     1
 Ministerio da Cultura";110.0                  1
 kulturelle Filmförderung des Bundes";141.0    1
Name: count, dtype: int64

In [19]:
df.drop("Unnamed: 2",axis=1,inplace=True)

In [20]:
#expanding the dataframe
expanded_dataframe = df.iloc[:,0].str.split(';',expand=True)
expanded_dataframe

,0,1,2,3,4,5,6,7,8,9,10
0,"1980 (United States)""",8.4,927000.0,"""Stanley Kubrick""","""Stephen King""","""Jack Nicholson""","""United Kingdom""",19000000,"""46998772.0""","""Warner Bros.""",146.0
1,"1980 (United States)""",5.8,65000.0,"""Randal Kleiser""","""Henry De Vere Stacpoole""","""Brooke Shields""","""United States""",4500000,"""58853106.0""","""Columbia Pictures""",104.0
2,"1980 (United States)""",8.7,1200000.0,"""Irvin Kershner""","""Leigh Brackett""","""Mark Hamill""","""United States""",18000000,"""538375067.0""","""Lucasfilm""",124.0
3,"1980 (United States)""",7.7,221000.0,"""Jim Abrahams""","""Jim Abrahams""","""Robert Hays""","""United States""",3500000,"""83453539.0""","""Paramount Pictures""",88.0
4,"1980 (United States)""",7.3,108000.0,"""Harold Ramis""","""Brian Doyle-Murray""","""Chevy Chase""","""United States""",6000000,"""39846344.0""","""Orion Pictures""",98.0
...,...,...,...,...,...,...,...,...,...,...,...
3995,"2002 (United States)""",6.1,25000.0,"""Jez Butterworth""","""Tom Butterworth""","""Nicole Kidman""","""United Kingdom""",13000000,"""16171098.0""","""FilmFour""",93.0
3996,"2001 (France)""",6.4,18000.0,"""Michel Gondry""","""Charlie Kaufman""","""Tim Robbins""","""France""",0,"""1574660.0""","""Fine Line Features""",96.0
3997,"2001 (United States)""",6.4,18000.0,"""Jon Favreau""","""Jon Favreau""","""Vince Vaughn""","""United States""",5000000,"""5480653.0""","""Artisan Entertainment""",95.0
3998,"2001 (United States)""",6.1,29000.0,"""Harald Zwart""","""Stan Seidel""","""Liv Tyler""","""United States""",18000000,"""13578186.0""","""October Films""",93.0
3999,"2001 (United States)""",4.7,42000.0,"""Steve Carr""","""Hugh Lofting""","""Eddie Murphy""","""United States""",70000000,"""176104344.0""","""Twentieth Century Fox""",87.0

In [21]:
df[['release_year_and_country',"score","votes","director","writer","star","country","budget","gross","company","runtime"]] = expanded_dataframe

In [22]:
df.head()

,Unnamed: 1,movie_name,rating_target_audience,genre,release_year,release_date,release_year_and_country,score,votes,director,writer,star,country,budget,gross,company,runtime
0,"1980 (United States)"";8.4;927000.0;""Stanley K...",The Shining,"""R""","""Drama""",1980,"""June 13","1980 (United States)""",8.4,927000.0,"""Stanley Kubrick""","""Stephen King""","""Jack Nicholson""","""United Kingdom""",19000000,"""46998772.0""","""Warner Bros.""",146.0
1,"1980 (United States)"";5.8;65000.0;""Randal Kle...",The Blue Lagoon,"""R""","""Adventure""",1980,"""July 2","1980 (United States)""",5.8,65000.0,"""Randal Kleiser""","""Henry De Vere Stacpoole""","""Brooke Shields""","""United States""",4500000,"""58853106.0""","""Columbia Pictures""",104.0
2,"1980 (United States)"";8.7;1200000.0;""Irvin Ke...",Star Wars: Episode V - The Empire Strikes Back,"""PG""","""Action""",1980,"""June 20","1980 (United States)""",8.7,1200000.0,"""Irvin Kershner""","""Leigh Brackett""","""Mark Hamill""","""United States""",18000000,"""538375067.0""","""Lucasfilm""",124.0
3,"1980 (United States)"";7.7;221000.0;""Jim Abrah...",Airplane!,"""PG""","""Comedy""",1980,"""July 2","1980 (United States)""",7.7,221000.0,"""Jim Abrahams""","""Jim Abrahams""","""Robert Hays""","""United States""",3500000,"""83453539.0""","""Paramount Pictures""",88.0
4,"1980 (United States)"";7.3;108000.0;""Harold Ra...",Caddyshack,"""R""","""Comedy""",1980,"""July 25","1980 (United States)""",7.3,108000.0,"""Harold Ramis""","""Brian Doyle-Murray""","""Chevy Chase""","""United States""",6000000,"""39846344.0""","""Orion Pictures""",98.0

In [23]:
#since we add extra columns, we can drop the original column
df.drop(df.columns[0],axis=1,inplace=True)

In [25]:
new_col = list()
col_list = ['rating_target_audience','genre','director','writer','star','country','company','gross']
for i in col_list:
    for j in df[i]:
        if type(j)==float:
            new_col.append(j)
        else:
            new_col.append(j[1:len(j)-1])
    df[i]=new_col
    new_col=[]

In [26]:
df

,movie_name,rating_target_audience,genre,release_year,release_date,release_year_and_country,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"""June 13","1980 (United States)""",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"""July 2","1980 (United States)""",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"""June 20","1980 (United States)""",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"""July 2","1980 (United States)""",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"""July 25","1980 (United States)""",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,R,Comedy,2001,"""February 1","2002 (United States)""",6.1,25000.0,Jez Butterworth,Tom Butterworth,Nicole Kidman,United Kingdom,13000000,16171098.0,FilmFour,93.0
3996,Human Nature,R,Comedy,2001,"""September 12","2001 (France)""",6.4,18000.0,Michel Gondry,Charlie Kaufman,Tim Robbins,France,0,1574660.0,Fine Line Features,96.0
3997,Made,R,Comedy,2001,"""August 31","2001 (United States)""",6.4,18000.0,Jon Favreau,Jon Favreau,Vince Vaughn,United States,5000000,5480653.0,Artisan Entertainment,95.0
3998,One Night at McCool's,R,Comedy,2001,"""April 27","2001 (United States)""",6.1,29000.0,Harald Zwart,Stan Seidel,Liv Tyler,United States,18000000,13578186.0,October Films,93.0
3999,Dr. Dolittle 2,PG,Comedy,2001,"""June 22","2001 (United States)""",4.7,42000.0,Steve Carr,Hugh Lofting,Eddie Murphy,United States,70000000,176104344.0,Twentieth Century Fox,87.0

In [27]:
new_col2 =list()
col_list2 = ['release_date','release_year_and_country']
for i in col_list2:
    if i=='release_date':
        for j in df[i]:
            if type(j)==float:
                new_col2.append(j)
            else:
                new_col2.append(j[1:])
        df[i]=new_col2
        new_col2 =[]
    else:
        for j in df[i]:
            if type(j)==float:
                new_col2.append(j)
            else:
                new_col2.append(j[:len(j)-1])
        df[i]=new_col2
        new_col2 =[]

In [28]:
df.isna().sum()

movie_name                   0
rating_target_audience       0
genre                        0
release_year                 0
release_date                 0
release_year_and_country    53
score                       53
votes                       53
director                    53
writer                      53
star                        53
country                     53
budget                      53
gross                       53
company                     53
runtime                     60
dtype: int64

In [29]:
import numpy as np

df[['release_year_and_country','director','writer','star','country','company']]=df.loc[:,['release_year_and_country','director','writer','star','country','company']].replace(np.nan,'not mentioned')

In [30]:
df.isna().sum()

movie_name                   0
rating_target_audience       0
genre                        0
release_year                 0
release_date                 0
release_year_and_country     0
score                       53
votes                       53
director                     0
writer                       0
star                         0
country                      0
budget                      53
gross                       53
company                      0
runtime                     60
dtype: int64

In [31]:
df[['score','votes','budget','gross','runtime']] = df.loc[:,['score','votes','budget','gross','runtime']].replace(np.nan,0)

In [32]:
df['gross'] = df['gross'].replace("",0)

In [33]:

df[['release_year','budget']] = df[['release_year','budget']].astype(int)

In [ ]:

df[['score','votes','gross']] = df[['score','votes','gross']].astype(float)

In [35]:
df.head()

,movie_name,rating_target_audience,genre,release_year,release_date,release_year_and_country,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,June 13,1980 (United States),8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,July 2,1980 (United States),5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,June 20,1980 (United States),8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,July 2,1980 (United States),7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,July 25,1980 (United States),7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98.0

In [37]:
df.dtypes

movie_name                   object
rating_target_audience       object
genre                        object
release_year                  int64
release_date                 object
release_year_and_country     object
score                       float64
votes                       float64
director                     object
writer                       object
star                         object
country                      object
budget                        int64
gross                       float64
company                      object
runtime                      object
dtype: object

In [38]:
df.to_csv('cleaned_movies.csv', index=False)